language: php
php:
  - 5.5
  - 5.4

before_script:
  - phpenv config-add .travis-config.ini
  - composer self-update
  - pecl install -f mongo-1.4.1
  - composer install --dev --prefer-source

services: 
  - mongodb